### ISSUE TITLE
Request - option to run custom function if JSLint fails

### ISSUE THREAD

**Issue by theaccordance** [stephenmathieson-boneyard/grunt-jslint#54]
Wanted to start a discussion here first before doing a pull-request or fork.  I'd like to have the ability to define a custom function to run if JSLint fails.  I'm working on moving my team's build processes into Grunt; having some flexibility on extending this plugin will be necessary to get buy-in.  

For my particular use case, I'm simply trying to invoke a say command so I receive an audible notification when linting fails.  Our team uses JSLint + a file watcher for continual linting during development, so we don't always have the console in the foreground.

**Comment by smikes** [comment]
PR is very welcome; please add unit tests to cover your changes, and honor the code style documented in .editorconfig.  Let us know if you have any questions as you're going along in case we can help.

Thanks!
